<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>About</title>

   <!-- swiper css link  -->
   <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

   <!-- font awesome cdn link  -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

   <!-- custom css file link  -->
   <link rel="stylesheet" href="style.css">

</head>
<body>
   
<!-- header section starts  -->

<section class="header">

   <a href="home.PHP" class="logo">Wedding Planner</a>

   <nav class="navbar">
      <a href="home.PHP">Home</a>
      <a href="about.PHP">About us</a>
      <a href="package.PHP">Services</a>
      <a href="book.PHP">Contact</a>
   </nav>

   <div id="menu-btn" class="fas fa-bars"></div>

</section>

<!-- header section ends -->


<!-- about section starts  -->

<section class="About">

   <div class="image">
      <img src="i.jpg">
   </div>

   <div class="content">
      <h3>Your Dream Wedding Starts Here</h3>
      <p>Welcome to our wedding planning company,where we turn your dreams into reality.We specialize in creating unforgettable moments for couples on their special day.</p>
      <div class="icons-container">
         <div class="icons">
            <i class="fas fa-map"></i>
            <span>Unique Themes</span>
         </div>
         <div class="icons">
            <i class="fas fa-hand-holding-usd"></i>
            <span>Personalized Services</span>
         </div>
         <div class="icons">
            <i class="fas fa-headset"></i>
            <span>Customized Packages</span>
         </div>
      </div>
   </div>

</section>

<!-- about section ends -->

<!-- reviews section starts  -->

<section class="testimonials">

   <h1 class="heading-title">Happy Couples</h1>

   <div class="swiper testimonials-slider">

      <div class="swiper-wrapper">

         <div class="swiper-slide slide">
            <div class="stars">
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
               <i class="fas fa-star"></i>
            </div>
            <p>Our wedding was beyond our wildest dreams.Thank you for making it so magical!!</p>
            <h2>Ajith & Prathima</h2>
            <span>Happy Couples</span>
         </div><br><br>

  
</section>

<!-- reviews section ends -->




<!-- footer section starts  -->

<section class="footer">

   <div class="box-container">

      <div class="box">
         <h3>quick links</h3>
         <a href="home.PHP"> <i class="fas fa-angle-right"></i> Home</a>
         <a href="about.PHP"> <i class="fas fa-angle-right"></i> About us</a>
         <a href="package.PHP"> <i class="fas fa-angle-right"></i> Services</a>
         <a href="book.PHP"> <i class="fas fa-angle-right"></i> Contact</a>
      </div>

      <div class="box">
         <h3>Extra Links</h3>
         <a href="#"> <i class="fas fa-angle-right"></i> FAQ's</a>
         <a href="#"> <i class="fas fa-angle-right"></i> Testimonials</a>
         <a href="#"> <i class="fas fa-angle-right"></i> Privacy Policy</a>
         <a href="#"> <i class="fas fa-angle-right"></i> Terms Of Use</a>
      </div>

      <div class="box">
         <h3>Contact Info</h3>
         <a href="#"> <i class="fas fa-phone"></i> 6361308284 </a>
         <a href="#"> <i class="fas fa-envelope"></i> nikhitham@gmail.com </a>
         <a href="#"> <i class="fas fa-map"></i> Giliyaru village post Kota,Brahmavara Taluk,Udupi dist </a>
      </div>

      <div class="box">
         <h3>Follow Us</h3>
         <a href="#"> <i class="fab fa-facebook-f"></i> Facebook </a>
         <a href="#"> <i class="fab fa-twitter"></i> Twitter </a>
         <a href="#"> <i class="fab fa-instagram"></i> Instagram </a>
         <a href="#"> <i class="fab fa-linkedin"></i> Linkedin </a>
      </div>

   </div>

   <div class="credit">  <span></span> All Rights reserved</div>

</section>

<!-- footer section ends -->
<!-- swiper js link  -->
<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

<!-- custom js file link  -->
<script src="script.js"></script>

</body>
</html>